### PR TITLE
Bug fix for combined cross sections

### PR DESCRIPTION
**Pull request by Naktakala**
Small bug fix when no fission cross-sections are present and user attempts to combine cross-sections.

### CODE REVIEW

**Comment by ragusa** [comment]
to combine cross-sections -->  to combine cross sections.  (No hyphen).

**Review by ragusa — APPROVED** [review]

**Review by ragusa — APPROVED** [review]
So, the atom density is in units of per barn-cm, right? Just making sure I understand the magnitude chosen for this test.

**Review by dominiccaron — COMMENTED** [review]
Would it not be better to make the reassignment after the completion of the ```for (auto combo : combinations)``` that begins on line 114, but before the statement ```double ff_i = N_i/Nf_total;``` on line 211? As ```Nf_total``` is accumulated within the for-loop identified above, if the direct assignment of ```1.0``` occurs within the for-loop, it can produce an incorrect value of the summation in various scenarios when it is not truly zero (or less than the imposed threshold).

**Comment by Naktakala** [comment]
> to combine cross-sections --> to combine cross sections. (No hyphen).

What was the convention again? cross-section and cross sections? Singular vs Plural?

**Comment by Naktakala** [comment]
> Would it not be better to make the reassignment after the completion of the `for (auto combo : combinations)` that begins on line 114, but before the statement `double ff_i = N_i/Nf_total;` on line 211? As `Nf_total` is accumulated within the for-loop identified above, if the direct assignment of `1.0` occurs within the for-loop, it can produce an incorrect value of the summation in various scenarios when it is not truly zero (or less than the imposed threshold).

You are correct. Watch how code-review just saved another bug.

**Review by dominiccaron — APPROVED** [review]

**Review by wdhawkins — APPROVED** [review]

**Comment by Naktakala** [comment]
> So, the atom density is in units of per barn-cm, right? Just making sure I understand the magnitude chosen for this test.

This class-unit is essentially dimensionless but LBS uses it as per barn-cm.

**Comment by ragusa** [comment]
cross-section library: hyphen because XS acts as an adjective in the compound noun

total cross section: no hyphe, XS acts as a noun

**Pull request merged**
